version: '3.7'

services:
  adoptly-database:
    image: bitnami/postgresql
    container_name: adoptly-database
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - adoptly-network
  
  adoptly-api:
    build:
      context: .
    container_name: adoptly-api
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@adoptly-database:5432/${POSTGRESQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - adoptly-database
    networks:
      - adoptly-network

networks:
  adoptly-network:
    driver: bridge
volumes:
  db:
  
